# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cambiar_visibilidad_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(408, 462)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 411, 461))
        self.label.setStyleSheet("background-image: url(:/newPrefix/interfaz.jpeg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/interfaz.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.btnIngresar_6 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_6.setGeometry(QtCore.QRect(60, 390, 71, 51))
        self.btnIngresar_6.setStyleSheet("background-color: rgb(124, 231, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_6.setObjectName("btnIngresar_6")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(130, 120, 121, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 341, 61))
        self.label_2.setStyleSheet("font: 87 25pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.btnIngresar_10 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_10.setGeometry(QtCore.QRect(260, 390, 101, 51))
        self.btnIngresar_10.setStyleSheet("background-color: rgb(124, 231, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_10.setObjectName("btnIngresar_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnIngresar_6.setText(_translate("Dialog", "salir"))
        self.label_2.setText(_translate("Dialog", "ID A MODIFICAR"))
        self.btnIngresar_10.setText(_translate("Dialog", "CAMBIAR"))
import prueba_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
