# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cambiar_visibilidad.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(339, 451)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 341, 451))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/interfaz.jpeg);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/interfaz.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.btnIngresar_15 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_15.setGeometry(QtCore.QRect(70, 60, 181, 51))
        self.btnIngresar_15.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_15.setObjectName("btnIngresar_15")
        self.btnIngresar_16 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_16.setGeometry(QtCore.QRect(70, 160, 181, 51))
        self.btnIngresar_16.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_16.setObjectName("btnIngresar_16")
        self.btnIngresar_17 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_17.setGeometry(QtCore.QRect(20, 390, 71, 51))
        self.btnIngresar_17.setStyleSheet("background-color: rgb(124, 231, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_17.setObjectName("btnIngresar_17")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnIngresar_15.setText(_translate("Dialog", "Cambiar a Visible"))
        self.btnIngresar_16.setText(_translate("Dialog", "Cambiar a Oculto"))
        self.btnIngresar_17.setText(_translate("Dialog", "Salir"))
import loginimag_rc
import prueba_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
