# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultar_entradas.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(341, 453)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 341, 451))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/interfaz.jpeg);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/interfaz.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.btnIngresar_11 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_11.setGeometry(QtCore.QRect(50, 60, 231, 51))
        self.btnIngresar_11.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_11.setObjectName("btnIngresar_11")
        self.btnIngresar_12 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_12.setGeometry(QtCore.QRect(50, 140, 231, 51))
        self.btnIngresar_12.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_12.setObjectName("btnIngresar_12")
        self.btnIngresar_13 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_13.setGeometry(QtCore.QRect(50, 220, 231, 51))
        self.btnIngresar_13.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_13.setObjectName("btnIngresar_13")
        self.btnIngresar_14 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_14.setGeometry(QtCore.QRect(30, 390, 71, 51))
        self.btnIngresar_14.setStyleSheet("background-color: rgb(124, 231, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_14.setObjectName("btnIngresar_14")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnIngresar_11.setText(_translate("Dialog", "Mostrar Registros Verdaderos"))
        self.btnIngresar_12.setText(_translate("Dialog", "Mostrar Registros Falsos"))
        self.btnIngresar_13.setText(_translate("Dialog", "Mostrar Todos los Registros"))
        self.btnIngresar_14.setText(_translate("Dialog", "Salir"))
import prueba_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
