# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grafica.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(341, 451)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 341, 451))
        self.label.setStyleSheet("background-image: url(:/newPrefix/interfaz.jpeg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/interfaz.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.btnIngresar_7 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_7.setGeometry(QtCore.QRect(40, 60, 261, 51))
        self.btnIngresar_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_7.setObjectName("btnIngresar_7")
        self.btnIngresar_8 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_8.setGeometry(QtCore.QRect(60, 150, 211, 51))
        self.btnIngresar_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_8.setObjectName("btnIngresar_8")
        self.btnIngresar_9 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_9.setGeometry(QtCore.QRect(20, 390, 71, 51))
        self.btnIngresar_9.setStyleSheet("background-color: rgb(124, 231, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_9.setObjectName("btnIngresar_9")
        self.btnIngresar_10 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_10.setGeometry(QtCore.QRect(250, 390, 71, 51))
        self.btnIngresar_10.setStyleSheet("background-color: rgb(124, 231, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_10.setObjectName("btnIngresar_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnIngresar_7.setText(_translate("Dialog", "Ver Graficas Individuales"))
        self.btnIngresar_8.setText(_translate("Dialog", "Ver Graficas Grupales"))
        self.btnIngresar_9.setText(_translate("Dialog", "Salir"))
        self.btnIngresar_10.setText(_translate("Dialog", "Grafica"))
import prueba_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
