# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu_Cam_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(341, 276)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 341, 451))
        self.label_5.setStyleSheet("background-image: url(:/newPrefix/interfaz.jpeg);")
        self.label_5.setText("")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setPixmap(QtGui.QPixmap(":/newPrefix/interfaz.jpeg"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(100, 0, 331, 61))
        self.label_6.setStyleSheet("font: 87 15pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 110, 221, 41))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(100, 30, 331, 61))
        self.label_7.setStyleSheet("font: 87 15pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.btnIngresar_22 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_22.setGeometry(QtCore.QRect(20, 250, 71, 21))
        self.btnIngresar_22.setStyleSheet("background-color: rgb(124, 231, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_22.setObjectName("btnIngresar_22")
        self.btnIngresar_23 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_23.setGeometry(QtCore.QRect(240, 250, 71, 21))
        self.btnIngresar_23.setStyleSheet("background-color: rgb(124, 231, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_23.setObjectName("btnIngresar_23")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Escriba Nueva "))
        self.label_7.setText(_translate("Dialog", "Hora del Turno"))
        self.btnIngresar_22.setText(_translate("Dialog", "Volver"))
        self.btnIngresar_23.setText(_translate("Dialog", "Guardar"))
import prueba_rc
