# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu_Cambio_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(344, 451)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 341, 451))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/interfaz.jpeg);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/interfaz.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.btnIngresar_18 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_18.setGeometry(QtCore.QRect(120, 130, 121, 41))
        self.btnIngresar_18.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_18.setObjectName("btnIngresar_18")
        self.btnIngresar_19 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_19.setGeometry(QtCore.QRect(120, 200, 121, 41))
        self.btnIngresar_19.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_19.setObjectName("btnIngresar_19")
        self.btnIngresar_20 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_20.setGeometry(QtCore.QRect(120, 270, 121, 41))
        self.btnIngresar_20.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_20.setObjectName("btnIngresar_20")
        self.btnIngresar_21 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_21.setGeometry(QtCore.QRect(20, 410, 71, 21))
        self.btnIngresar_21.setStyleSheet("background-color: rgb(124, 231, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_21.setObjectName("btnIngresar_21")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 331, 61))
        self.label_4.setStyleSheet("font: 87 15pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnIngresar_18.setText(_translate("Dialog", "Turno 1"))
        self.btnIngresar_19.setText(_translate("Dialog", "Turno 2"))
        self.btnIngresar_20.setText(_translate("Dialog", "Turno 3"))
        self.btnIngresar_21.setText(_translate("Dialog", "Salir"))
        self.label_4.setText(_translate("Dialog", "Seleccione Turno a Modificar"))
import prueba_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())