# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grafica.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets

import sys
sys.path.append(r"D:\crisg\GitHub\trabajo\CORPOGAS_2\CD")

from Grafica import leer_registros, generar_grafica_por_empleado, generar_grafica_grupal

class Ui_Dialog(object):

    def setupUi(self, Dialog, parent=None):
        
        self.parent = parent
        self.Dialog = Dialog

        Dialog.setObjectName("Dialog")
        Dialog.resize(341, 451)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 341, 451))
        self.label.setStyleSheet("background-image: url(:/newPrefix/interfaz.jpeg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/interfaz.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        # BOTÓN: Ver gráficas individuales
        self.btnIngresar_7 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_7.setGeometry(QtCore.QRect(20, 60, 281, 51))
        self.btnIngresar_7.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, "
            "stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));"
            "font: 87 10pt \"Arial Black\";"
        )
        self.btnIngresar_7.setObjectName("btnIngresar_7")

        # BOTÓN: Ver gráficas grupales
        self.btnIngresar_8 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_8.setGeometry(QtCore.QRect(30, 150, 241, 51))
        self.btnIngresar_8.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, "
            "stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));"
            "font: 87 10pt \"Arial Black\";"
        )
        self.btnIngresar_8.setObjectName("btnIngresar_8")

        # BOTÓN: VOLVER
        self.btnIngresar_9 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_9.setGeometry(QtCore.QRect(90, 230, 101, 51))
        self.btnIngresar_9.setStyleSheet(
            "background-color: rgb(124, 231, 255);"
            "font: 87 10pt \"Arial Black\";"
        )
        self.btnIngresar_9.setObjectName("btnIngresar_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)



        self.btnIngresar_7.clicked.connect(self.mostrar_grafica_individual)
        self.btnIngresar_8.clicked.connect(self.mostrar_grafica_grupal)

        # CORREGIDO → Ahora llama a self.volver() en lugar de cerrar directamente
        self.btnIngresar_9.clicked.connect(self.volver)


    def volver(self):
        """Cerrar la pantalla actual y regresar al menú principal."""
        if self.parent is not None:
            self.parent.show()

        self.Dialog.close()



    def mostrar_grafica_individual(self):
        registros = leer_registros()

        empleado, ok = QtWidgets.QInputDialog.getText(
            None,
            "Empleado",
            "Ingresa el nombre del empleado:"
        )

        if ok and empleado.strip():
            generar_grafica_por_empleado(registros, empleado.strip())



    def mostrar_grafica_grupal(self):
        registros = leer_registros()
        generar_grafica_grupal(registros)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Gráficas"))
        self.btnIngresar_7.setText(_translate("Dialog", "Ver Graficas Individuales"))
        self.btnIngresar_8.setText(_translate("Dialog", "Ver Graficas Grupales"))
        self.btnIngresar_9.setText(_translate("Dialog", "VOLVER"))


import prueba_rc

#if __name__ == "__main__":
 #   app = QtWidgets.QApplication(sys.argv)
  #  Dialog = QtWidgets.QDialog()
   # ui = Ui_Dialog()
    #ui.setupUi(Dialog)
    #Dialog.show()
    #sys.exit(app.exec_())