# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from Menu_registro_empleado import Ui_Dialog as RegistroEmpleadoUI
from consultar_entradas import ConsultarEntradasVentana
from grafica import Ui_Dialog as GraficaUI

class MenuPrincipal(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Menú Principal")
        self.resize(431, 541)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(0, 0, 431, 541))
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/interfaz.jpeg"))
        self.label.setScaledContents(True)
        self.btnIngresar = QtWidgets.QPushButton(self)
        self.btnIngresar.setGeometry(QtCore.QRect(70, 80, 291, 51))
        self.btnIngresar.setStyleSheet("font: 87 12pt 'Arial Black';")
        self.btnIngresar.setText("Registrar empleado")
        self.btnIngresar_2 = QtWidgets.QPushButton(self)
        self.btnIngresar_2.setGeometry(QtCore.QRect(70, 160, 291, 51))
        self.btnIngresar_2.setStyleSheet("font: 87 12pt 'Arial Black';")
        self.btnIngresar_2.setText("Consultar entradas")
        self.btnIngresar_3 = QtWidgets.QPushButton(self)
        self.btnIngresar_3.setGeometry(QtCore.QRect(70, 240, 291, 51))
        self.btnIngresar_3.setStyleSheet("font: 87 12pt 'Arial Black';")
        self.btnIngresar_3.setText("Ver Gráficas")
        self.btnIngresar_4 = QtWidgets.QPushButton(self)
        self.btnIngresar_4.setGeometry(QtCore.QRect(70, 320, 291, 51))
        self.btnIngresar_4.setStyleSheet("font: 87 12pt 'Arial Black';")
        self.btnIngresar_4.setText("Configurar horarios")

        # ESTE ES EL BOTÓN QUE TE FALTABA CONECTAR
        self.btnIngresar_5 = QtWidgets.QPushButton(self)
        self.btnIngresar_5.setGeometry(QtCore.QRect(70, 400, 291, 51))
        self.btnIngresar_5.setStyleSheet("font: 87 12pt 'Arial Black';")
        self.btnIngresar_5.setText("Cambiar visibilidad")
        self.btnIngresar_6 = QtWidgets.QPushButton(self)
        self.btnIngresar_6.setGeometry(QtCore.QRect(70, 480, 291, 51))
        self.btnIngresar_6.setStyleSheet("font: 87 12pt 'Arial Black'; background-color: rgb(124, 231, 255);")
        self.btnIngresar_6.setText("Salir")
        self.btnIngresar.clicked.connect(self.abrir_registro_empleado)
        self.btnIngresar_2.clicked.connect(self.abrir_consultar_entradas)
        self.btnIngresar_3.clicked.connect(self.abrir_graficas)
        self.btnIngresar_4.clicked.connect(self.abrir_cambiar_horarios)
        self.btnIngresar_5.clicked.connect(self.abrir_cambiar_visibilidad)
        self.btnIngresar_6.clicked.connect(self.close)

    
    def abrir_registro_empleado(self):
        self.registro_win = QtWidgets.QDialog()
        self.registro_ui = RegistroEmpleadoUI()
        self.registro_ui.setupUi(self.registro_win)
        self.registro_ui.btnIngresar_2.clicked.connect(self.volver_menu)
        self.registro_win.show()
        self.hide()

    
    def abrir_consultar_entradas(self):
        self.consultar_win = ConsultarEntradasVentana(self)
        self.consultar_win.show()
        self.hide()

    
    def abrir_graficas(self):
        self.grafica_win = QtWidgets.QDialog()
        self.grafica_ui = GraficaUI()
        self.grafica_ui.setupUi(self.grafica_win)
        self.grafica_ui.btnIngresar_9.clicked.connect(self.volver_menu)
        self.grafica_win.show()
        self.hide()


    def abrir_cambiar_horarios(self):
        from Cmbiar_hurat import Ui_Dialog
        self.cambiar_win = QtWidgets.QDialog()
        self.cambiar_ui = Ui_Dialog()
        self.cambiar_ui.setupUi(self.cambiar_win)
        self.cambiar_ui.btnIngresar_2.clicked.connect(self.volver_menu)
        self.cambiar_win.show()
        self.hide()


    def abrir_cambiar_visibilidad(self):
        from camviar_visisbilidad import Ui_Dialog as CambiarVisUI

        self.visibilidad_win = QtWidgets.QDialog()
        self.visibilidad_ui = CambiarVisUI()
        self.visibilidad_ui.setupUi(self.visibilidad_win)

        # Conectar botón VOLVER
        self.visibilidad_ui.btnIngresar_17.clicked.connect(self.volver_menu)

        self.visibilidad_win.show()
        self.hide()

   
    def volver_menu(self):
        self.show()

        for ventana in [
            "registro_win", "consultar_win",
            "grafica_win", "cambiar_win",
            "visibilidad_win"
        ]:
            try:
                getattr(self, ventana).close()
            except:
                pass


#if __name__ == "__main__":
 #   import sys
  #  app = QtWidgets.QApplication(sys.argv)
   # win = MenuPrincipal()
    #win.show()
    #sys.exit(app.exec_())