# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu_registro_empleado.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets


# Ruta donde está Registro_empleados.py
sys.path.append(r"D:\crisg\GitHub\trabajo\CORPOGAS_2\CD")

# Ruta donde está la carpeta TXT (para horarios.txt, entradas.txt, usuarios.txt)
os.chdir(r"D:\crisg\GitHub\trabajo\CORPOGAS_2")

# Importar función principal
from Registro_empleados import guardar_entrada


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(737, 849)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 741, 851))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("background-image: url(:/newPrefix/interfaz.jpeg);")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/interfaz.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.leUsuario_2 = QtWidgets.QLineEdit(Dialog)
        self.leUsuario_2.setGeometry(QtCore.QRect(200, 150, 201, 31))
        self.leUsuario_2.setObjectName("leUsuario_2")

        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(180, 70, 251, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setStyleSheet("color: black;")

        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(80, 300, 95, 20))
        self.radioButton.setStyleSheet("color: white;")
        self.radioButton.setObjectName("radioButton")

        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(230, 300, 95, 20))
        self.radioButton_2.setStyleSheet("color: white;")
        self.radioButton_2.setObjectName("radioButton_2")

        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(420, 300, 95, 20))
        self.radioButton_3.setStyleSheet("color: white;")
        self.radioButton_3.setObjectName("radioButton_3")

        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(200, 230, 211, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_2.setStyleSheet("color: black;")

        self.textBrowser_3 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(130, 420, 361, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_3.setStyleSheet("color: black;")

        self.leUsuario_3 = QtWidgets.QLineEdit(Dialog)
        self.leUsuario_3.setGeometry(QtCore.QRect(200, 490, 201, 31))
        self.leUsuario_3.setObjectName("leUsuario_3")

        self.btnIngresar = QtWidgets.QPushButton(Dialog)
        self.btnIngresar.setGeometry(QtCore.QRect(230, 580, 121, 31))
        self.btnIngresar.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, "
            "stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));"
            "font: 87 10pt \"Arial Black\";"
        )
        self.btnIngresar.setObjectName("btnIngresar")

        self.btnIngresar_2 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_2.setGeometry(QtCore.QRect(130, 740, 121, 31))
        self.btnIngresar_2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, "
            "stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));"
            "font: 87 10pt \"Arial Black\";"
        )
        self.btnIngresar_2.setObjectName("btnIngresar_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

        self.leUsuario_2.setText(_translate("Dialog", "Nombre de Usuario"))
        self.radioButton.setText(_translate("Dialog", "Turno 1"))
        self.radioButton_2.setText(_translate("Dialog", "Turno 2"))
        self.radioButton_3.setText(_translate("Dialog", "Turno 3"))

        self.textBrowser.setHtml(_translate("Dialog", "<p style='font-size:12pt;'>Registro de Empleados</p>"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<p style='font-size:12pt;'>Seleccione Turno</p>"))
        self.textBrowser_3.setHtml(_translate("Dialog", "<p style='font-size:12pt;'>Ingresar Fecha y Hora de Entrada</p>"))

        self.leUsuario_3.setText(_translate("Dialog", "AAAA-MM-DD HH:MM:SS"))
        self.btnIngresar.setText(_translate("Dialog", "INGRESAR"))
        self.btnIngresar_2.setText(_translate("Dialog", "volver"))


import prueba_rc



class RegistroVentana(QtWidgets.QDialog):
    def __init__(self, parent_menu=None):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)

        # Botón "volver" → cierra ventana
        self.ui.btnIngresar_2.clicked.connect(self.volver_menu)

        # Botón "INGRESAR" → guardar en TXT
        self.ui.btnIngresar.clicked.connect(self.guardar_datos)

    def volver_menu(self):
        self.close()

    def guardar_datos(self):
        empleado = self.ui.leUsuario_2.text().strip()

        if self.ui.radioButton.isChecked():
            turno = 1
        elif self.ui.radioButton_2.isChecked():
            turno = 2
        elif self.ui.radioButton_3.isChecked():
            turno = 3
        else:
            turno = 1

        fecha_hora = self.ui.leUsuario_3.text().strip()

        guardar_entrada(empleado, turno, fecha_hora)

        QtWidgets.QMessageBox.information(
            self, "Registro guardado", "La entrada fue registrada correctamente."
        )



        self.ui.leUsuario_2.clear()         
        self.ui.leUsuario_3.clear()         

        self.ui.radioButton.setChecked(False)
        self.ui.radioButton_2.setChecked(False)
        self.ui.radioButton_3.setChecked(False)


#if __name__ == "__main__":
 #   import sys
  #  app = QtWidgets.QApplication(sys.argv)
   # win = RegistroVentana()
    #win.show()
    #sys.exit(app.exec_())