# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registro_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import os


# AÑADIR CARPETA RAÍZ DEL PROYECTO (CORPOGAS_2) AL PATH
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from CD.Login import registrar_usuario, iniciar_sesion
from PyQt5 import QtCore, QtGui, QtWidgets
import prueba_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(437, 422)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 441, 421))
        self.label.setStyleSheet("background-image: url(:/newPrefix/fondologin.jpeg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/fondologin.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.leUsuario = QtWidgets.QLineEdit(Dialog)
        self.leUsuario.setGeometry(QtCore.QRect(90, 90, 191, 20))
        self.leUsuario.setObjectName("leUsuario")

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 361, 51))
        self.label_2.setStyleSheet("font: 87 25pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setIndent(-6)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")

        self.lePass = QtWidgets.QLineEdit(Dialog)
        self.lePass.setGeometry(QtCore.QRect(90, 130, 191, 20))
        self.lePass.setObjectName("lePass")

        # OCULTAR CONTRASEÑA
        self.lePass.setEchoMode(QtWidgets.QLineEdit.Password)

        self.btnIngresar = QtWidgets.QPushButton(Dialog)
        self.btnIngresar.setGeometry(QtCore.QRect(120, 160, 121, 31))
        self.btnIngresar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar.setObjectName("btnIngresar")

        #  CONECTAR BOTÓN AL MÉTODO QUE REGISTRA
        self.btnIngresar.clicked.connect(self.registrar)

        self.btnIngresar_3 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_3.setGeometry(QtCore.QRect(10, 360, 121, 31))
        self.btnIngresar_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 10pt \"Arial Black\";")
        self.btnIngresar_3.setObjectName("btnIngresar_3")

        #CONECTAR BOTÓN VOLVER
        self.btnIngresar_3.clicked.connect(self.volver)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def volver(self):
        from login2 import Ui_Dialog as LoginDialog   # ← Se importa dentro de la función
        self.login = QtWidgets.QDialog()
        self.ui_login = LoginDialog()
        self.ui_login.setupUi(self.login)
        self.login.show()

    def registrar(self):
        usuario = self.leUsuario.text()
        contraseña = self.lePass.text()

        if usuario == "" or contraseña == "":
            QtWidgets.QMessageBox.warning(None, "Error", "Debes llenar ambos campos.")
            return

        registrar_usuario(usuario, contraseña)

        QtWidgets.QMessageBox.information(None, "Éxito", "Usuario registrado correctamente.")
        self.leUsuario.clear()
        self.lePass.clear()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.leUsuario.setPlaceholderText(_translate("Dialog", "Ingresa tu Usuario"))
        self.label_2.setText(_translate("Dialog", " Nuevo Usuario y contraseña "))
        self.lePass.setPlaceholderText(_translate("Dialog", "Ingresa tu Contraseña"))
        self.btnIngresar.setText(_translate("Dialog", "INGRESAR"))
        self.btnIngresar_3.setText(_translate("Dialog", "VOLVER"))


#if __name__ == "__main__":
 #   app = QtWidgets.QApplication(sys.argv)
  #  Dialog = QtWidgets.QDialog()
   # ui = Ui_Dialog()
    #ui.setupUi(Dialog)
    #Dialog.show()
    #sys.exit(app.exec_())