# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camviar_visisbilidad.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
import prueba_rc
import sys

# RUTA DONDE ESTÁ REGISTRO_EMPLEADOS.PY
sys.path.append(r"D:\crisg\GitHub\trabajo\CORPOGAS_2\CD")

# IMPORTAMOS LA FUNCIÓN REAL
from Registro_empleados import cambiar_visibilidad_manual


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(535, 673)

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 541, 671))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/interfaz.jpeg);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/interfaz.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.btnIngresar_16 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_16.setGeometry(QtCore.QRect(150, 350, 181, 51))
        self.btnIngresar_16.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));"
            "font: 87 10pt 'Arial Black';")
        self.btnIngresar_16.setObjectName("btnIngresar_16")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(150, 80, 201, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.leUsuario_2 = QtWidgets.QLineEdit(Dialog)
        self.leUsuario_2.setGeometry(QtCore.QRect(140, 220, 201, 31))
        self.leUsuario_2.setObjectName("leUsuario_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(120, 160, 271, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.btnIngresar_15 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_15.setGeometry(QtCore.QRect(150, 280, 181, 51))
        self.btnIngresar_15.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255));"
            "font: 87 10pt 'Arial Black';")
        self.btnIngresar_15.setObjectName("btnIngresar_15")
        self.btnIngresar_17 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_17.setGeometry(QtCore.QRect(170, 440, 121, 41))
        self.btnIngresar_17.setStyleSheet(
            "background-color: rgb(124, 231, 255);"
            "font: 87 10pt 'Arial Black';")
        self.btnIngresar_17.setObjectName("btnIngresar_17")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cambiar Visibilidad"))
        self.btnIngresar_16.setText(_translate("Dialog", "Cambiar a Oculto"))
        self.textBrowser.setHtml(_translate("Dialog",
            "<p style='font-size:10pt;'>CAMBIAR VISIBILIDAD</p>"))
        self.leUsuario_2.setText(_translate("Dialog", "ID DEL REGISTRO"))
        self.textBrowser_2.setHtml(_translate("Dialog",
            "<p style='font-size:10pt;'>SELECCIONAR ID DEL REGISTRO</p>"))
        self.btnIngresar_15.setText(_translate("Dialog", "Cambiar a Visible"))
        self.btnIngresar_17.setText(_translate("Dialog", "VOLVER"))




class CambiarVisibilidadWindow(QtWidgets.QDialog):
    def __init__(self, menu_padre):
        super().__init__()
        self.menu_padre = menu_padre

        self.ui = Ui_Dialog()
        self.ui.setupUi(self)

        # BOTONES DE CAMBIO DE VISIBILIDAD
        self.ui.btnIngresar_15.clicked.connect(self.cambiar_visible)
        self.ui.btnIngresar_16.clicked.connect(self.cambiar_oculto)

        # BOTÓN VOLVER
        self.ui.btnIngresar_17.clicked.connect(self.volver_menu)


    def cambiar_visible(self):
        id_texto = self.ui.leUsuario_2.text().strip()

        if not id_texto.isdigit():
            QtWidgets.QMessageBox.warning(self, "Error", "El ID debe ser un número.")
            return

        exito = cambiar_visibilidad_manual(int(id_texto), "V")

        if exito:
            QtWidgets.QMessageBox.information(self, "Éxito", "Visibilidad cambiada a VISIBLE.")
        else:
            QtWidgets.QMessageBox.warning(self, "Error", "No se encontró el ID.")


    def cambiar_oculto(self):
        id_texto = self.ui.leUsuario_2.text().strip()

        if not id_texto.isdigit():
            QtWidgets.QMessageBox.warning(self, "Error", "El ID debe ser un número.")
            return

        exito = cambiar_visibilidad_manual(int(id_texto), "F")

        if exito:
            QtWidgets.QMessageBox.information(self, "Éxito", "Visibilidad cambiada a OCULTO.")
        else:
            QtWidgets.QMessageBox.warning(self, "Error", "No se encontró el ID.")


    def volver_menu(self):
        self.menu_padre.show()
        self.close()


# ========================================================
#        EJECUCIÓN DIRECTA
# ========================================================
#if __name__ == "__main__":
   # app = QtWidgets.QApplication(sys.argv)
    #win = CambiarVisibilidadWindow(None)
    #win.show()
    #sys.exit(app.exec_())