# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultar_entradas.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

# ARCHIVO CORREGIDO PARA USAR CORPOGAS_2
ARCHIVO_ENTRADAS = r"D:\crisg\GitHub\trabajo\CORPOGAS_2\TXT\entradas.txt"


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(341, 453)

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 341, 451))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/interfaz.jpeg);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/interfaz.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.btnIngresar_11 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_11.setGeometry(QtCore.QRect(20, 60, 291, 51))
        self.btnIngresar_11.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255)); font: 87 10pt \"Arial Black\";")
        self.btnIngresar_11.setObjectName("btnIngresar_11")
        self.btnIngresar_12 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_12.setGeometry(QtCore.QRect(30, 140, 281, 51))
        self.btnIngresar_12.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255)); font: 87 10pt \"Arial Black\";")
        self.btnIngresar_12.setObjectName("btnIngresar_12")
        self.btnIngresar_13 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_13.setGeometry(QtCore.QRect(30, 220, 281, 51))
        self.btnIngresar_13.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(255, 255, 255, 255)); font: 87 10pt \"Arial Black\";")
        self.btnIngresar_13.setObjectName("btnIngresar_13")
        self.btnIngresar_14 = QtWidgets.QPushButton(Dialog)
        self.btnIngresar_14.setGeometry(QtCore.QRect(30, 390, 71, 51))
        self.btnIngresar_14.setStyleSheet("background-color: rgb(124, 231, 255); font: 87 10pt \"Arial Black\";")
        self.btnIngresar_14.setObjectName("btnIngresar_14")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Consultar Entradas"))
        self.btnIngresar_11.setText(_translate("Dialog", "Mostrar Registros Verdaderos"))
        self.btnIngresar_12.setText(_translate("Dialog", "Mostrar Registros Falsos"))
        self.btnIngresar_13.setText(_translate("Dialog", "Mostrar Todos los Registros"))
        self.btnIngresar_14.setText(_translate("Dialog", "Salir"))


class ConsultarEntradasVentana(QtWidgets.QDialog):
    def __init__(self, menu_principal):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        self.menu_principal = menu_principal
        self.ui.btnIngresar_14.clicked.connect(self.volver_menu)
        self.ui.btnIngresar_11.clicked.connect(self.mostrar_verdaderos)
        self.ui.btnIngresar_12.clicked.connect(self.mostrar_falsos)
        self.ui.btnIngresar_13.clicked.connect(self.mostrar_todos)

    def volver_menu(self):
        self.close()
        self.menu_principal.show()

    def mostrar_verdaderos(self):
        self.mostrar_registros("V")

    def mostrar_falsos(self):
        self.mostrar_registros("F")

    def mostrar_todos(self):
        self.mostrar_registros("ALL")

    def mostrar_registros(self, tipo):
        if not os.path.exists(ARCHIVO_ENTRADAS):
            QtWidgets.QMessageBox.information(self, "Sin datos", "No existe el archivo de entradas.")
            return

        with open(ARCHIVO_ENTRADAS, "r", encoding="utf-8") as f:
            lineas = f.readlines()

        resultados = []

        for linea in lineas:
            linea = linea.strip()
            if tipo == "V" and linea.endswith("V"):
                resultados.append(linea)
            elif tipo == "F" and linea.endswith("F"):
                resultados.append(linea)
            elif tipo == "ALL":
                resultados.append(linea)
        if not resultados:
            QtWidgets.QMessageBox.information(self, "Sin resultados", "No se encontraron registros.")
            return

        msg = "\n".join(resultados)
        QtWidgets.QMessageBox.information(self, "Resultados", msg)


import prueba_rc



#if __name__ == "__main__":
 #   import sys
  #  app = QtWidgets.QApplication(sys.argv)
   # win = ConsultarEntradasVentana(None)
    #win.show()
    #sys.exit(app.exec_())